In [16]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.stats.api as sms
from IPython.display import display
from statsmodels.stats.stattools import durbin_watson

donnees = "relationsalairesperformance.xlsx"
df_salaire_performance = pd.read_excel(donnees)
print (df_salaire_performance)
X=df_salaire_performance['salaire']
X = sm.add_constant(X)
Y = df_salaire_performance['nombre_de_points']
model = sm.OLS(Y, X).fit()
print(model.summary())
white_test = sms.het_white(model.resid,model.model.exog)
lm_stat = white_test[0]
lm_pvalue = white_test[1]
f_stat = white_test[2]
f_pvalue = white_test[3]
print("\nHeteroskedasticity Test : white")
print("="*55)
print (f"{'F-statistic':<20} {f_stat:>12.6f} {'Prob. F':<20} {f_pvalue:>10.4f}")
print(f"{'Obs*R-squared':<20} {lm_stat:>12.6f} {'Prob. Chi-Square':<20} {lm_pvalue:>10.4f}")
print("="*55)
labels = ["LM statistic","LM p-value", "F-statistic", "F p-value"]
results_df = pd.DataFrame({"Statistique":labels,"Valeur":white_test})
print(results_df)
display(results_df)

           Club  nombre_de_points  salaire
0        Angers                36    21.48
1       Auxerre                42    18.68
2         Brest                50    30.53
3      Le Havre                34    17.15
4          Lens                52    31.19
5         Lille                60    44.81
6          Lyon                57    64.84
7     Marseille                65    78.03
8        Monaco                61    52.49
9   Montpellier                16    16.61
10       Nantes                36    30.71
11         Nice                60    57.67
12          PSG                84   250.80
13        Reims                33    17.13
14       Rennes                41    42.18
15         ASSE                30    15.00
16   Strasbourg                57    20.86
17     Toulouse                42    19.64
                            OLS Regression Results
==============================================================================
Dep. Variable:       nombre_de_points   R-squared:                       0.560
Model:                            OLS   Adj. R-squared:                  0.533
Method:                 Least Squares   F-statistic:                     20.40
Date:                Fri, 15 May 2026   Prob (F-statistic):           0.000351
Time:                        09:27:15   Log-Likelihood:                -67.631
No. Observations:                  18   AIC:                             139.3
Df Residuals:                      16   BIC:                             141.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         37.3580      3.437     10.870      0.000      30.072      44.644
salaire        0.2212      0.049      4.516      0.000       0.117       0.325
==============================================================================
Omnibus:                        1.016   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.602   Jarque-Bera (JB):                0.745
Skew:                          -0.467   Prob(JB):                        0.689
Kurtosis:                       2.651   Cond. No.                         93.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Heteroskedasticity Test : white
=======================================================
F-statistic              0.205312 Prob. F                  0.8166
Obs*R-squared            0.479620 Prob. Chi-Square         0.7868
=======================================================
    Statistique    Valeur
0  LM statistic  0.479620
1    LM p-value  0.786777
2   F-statistic  0.205312
3     F p-value  0.816644

    Statistique    Valeur
0  LM statistic  0.479620
1    LM p-value  0.786777
2   F-statistic  0.205312
3     F p-value  0.816644

In [16]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.stats.api as sms
from IPython.display import display
from statsmodels.stats.stattools import durbin_watson

donnees = "relationsalairesperformance.xlsx"
df_salaire_performance = pd.read_excel(donnees)
print (df_salaire_performance)
X=df_salaire_performance['salaire']
X = sm.add_constant(X)
Y = df_salaire_performance['nombre_de_points']
model = sm.OLS(Y, X).fit()
print(model.summary())
white_test = sms.het_white(model.resid,model.model.exog)
lm_stat = white_test[0]
lm_pvalue = white_test[1]
f_stat = white_test[2]
f_pvalue = white_test[3]
print("\nHeteroskedasticity Test : white")
print("="*55)
print (f"{'F-statistic':<20} {f_stat:>12.6f} {'Prob. F':<20} {f_pvalue:>10.4f}")
print(f"{'Obs*R-squared':<20} {lm_stat:>12.6f} {'Prob. Chi-Square':<20} {lm_pvalue:>10.4f}")
print("="*55)
labels = ["LM statistic","LM p-value", "F-statistic", "F p-value"]
results_df = pd.DataFrame({"Statistique":labels,"Valeur":white_test})
print(results_df)
display(results_df)

           Club  nombre_de_points  salaire
0        Angers                36    21.48
1       Auxerre                42    18.68
2         Brest                50    30.53
3      Le Havre                34    17.15
4          Lens                52    31.19
5         Lille                60    44.81
6          Lyon                57    64.84
7     Marseille                65    78.03
8        Monaco                61    52.49
9   Montpellier                16    16.61
10       Nantes                36    30.71
11         Nice                60    57.67
12          PSG                84   250.80
13        Reims                33    17.13
14       Rennes                41    42.18
15         ASSE                30    15.00
16   Strasbourg                57    20.86
17     Toulouse                42    19.64
                            OLS Regression Results
==============================================================================
Dep. Variable:       nombre_de_points   R-squared:                       0.560
Model:                            OLS   Adj. R-squared:                  0.533
Method:                 Least Squares   F-statistic:                     20.40
Date:                Fri, 15 May 2026   Prob (F-statistic):           0.000351
Time:                        09:27:15   Log-Likelihood:                -67.631
No. Observations:                  18   AIC:                             139.3
Df Residuals:                      16   BIC:                             141.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         37.3580      3.437     10.870      0.000      30.072      44.644
salaire        0.2212      0.049      4.516      0.000       0.117       0.325
==============================================================================
Omnibus:                        1.016   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.602   Jarque-Bera (JB):                0.745
Skew:                          -0.467   Prob(JB):                        0.689
Kurtosis:                       2.651   Cond. No.                         93.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Heteroskedasticity Test : white
=======================================================
F-statistic              0.205312 Prob. F                  0.8166
Obs*R-squared            0.479620 Prob. Chi-Square         0.7868
=======================================================
    Statistique    Valeur
0  LM statistic  0.479620
1    LM p-value  0.786777
2   F-statistic  0.205312
3     F p-value  0.816644

    Statistique    Valeur
0  LM statistic  0.479620
1    LM p-value  0.786777
2   F-statistic  0.205312
3     F p-value  0.816644